/** AREA: STYLIST CODER MODEL -> AUTO-GENERATED */
export {
	BACKLOG_DEFAULT_JSON_PATH,
	BACKLOG_HISTORY_DIRECTORY_PATH,
	BACKLOG_JSONL_DIRECTORY_PATH,
	BUILDER_LAYOUT_LIB_PATH,
	CONTENT_PREVIEW_MAX_FILE_SIZE,
	ERROR_LOG_FILE,
	ISSUES_JSONL_PATH,
	LIB_DIRECTORY_PATH
} from './value';
