export function buildTemplateLayoutSource(input: {
	family: string;
	sections: Array<{ id: string; columns: number; items: string[][] }>;
	instances: Array<{ id: string; componentPath: string; config: Record<string, unknown> }>;
}): string {
	type ImportEntry = { identifier: string; componentPath: string };

	function toPascalCase(familySegment: string): string {
		return familySegment
			.split(/[-_]+/)
			.filter(Boolean)
			.map((word) => word.charAt(0).toUpperCase() + word.slice(1))
			.join('');
	}

	function toImportSpecifier(componentPath: string): string {
		const normalized = componentPath.replace(/\\/g, '/').replace(/\/index\.svelte$/, '');
		return `$stylist/${normalized}/index.svelte`;
	}

	function familySegmentFromPath(componentPath: string): string {
		const segments = componentPath.replace(/\\/g, '/').split('/');
		const familyIndex = segments.indexOf('component') + 2;
		return segments[familyIndex] ?? segments.at(-2) ?? 'component';
	}

	function assignImportIdentifiers(
		instances: Array<{ componentPath: string }>
	): Map<string, ImportEntry> {
		const byComponentPath = new Map<string, ImportEntry>();
		const usedIdentifiers = new Set<string>();

		for (const instance of instances) {
			if (byComponentPath.has(instance.componentPath)) {
				continue;
			}

			const baseIdentifier = toPascalCase(familySegmentFromPath(instance.componentPath)) || 'Component';
			let identifier = baseIdentifier;
			let suffix = 2;
			while (usedIdentifiers.has(identifier)) {
				identifier = `${baseIdentifier}${suffix}`;
				suffix += 1;
			}

			usedIdentifiers.add(identifier);
			byComponentPath.set(instance.componentPath, { identifier, componentPath: instance.componentPath });
		}

		return byComponentPath;
	}

	function serializeProps(config: Record<string, unknown>): string {
		const entries = Object.entries(config);
		if (entries.length === 0) {
			return '';
		}

		const attrs = entries.map(([key, value]) => `${key}={${JSON.stringify(value)}}`);
		return ` ${attrs.join(' ')}`;
	}

	const importsByPath = assignImportIdentifiers(input.instances);
	const instanceById = new Map(input.instances.map((instance) => [instance.id, instance]));

	const importLines = [...importsByPath.values()]
		.sort((left, right) => left.identifier.localeCompare(right.identifier))
		.map((entry) => `\timport ${entry.identifier} from '${toImportSpecifier(entry.componentPath)}';`)
		.join('\n');

	const sectionsMarkup = input.sections
		.map((section) => {
			const columnsMarkup = section.items
				.map((columnItems) => {
					const componentsMarkup = columnItems
						.map((instanceId) => {
							const instance = instanceById.get(instanceId);
							if (!instance) return '';
							const importEntry = importsByPath.get(instance.componentPath);
							if (!importEntry) return '';
							return `\t\t\t<${importEntry.identifier}${serializeProps(instance.config)} />`;
						})
						.filter(Boolean)
						.join('\n');

					return `\t\t<div class="t-column">\n${componentsMarkup}\n\t\t</div>`;
				})
				.join('\n');

			return `\t<section class="t-section t-section--cols-${section.columns}">\n${columnsMarkup}\n\t</section>`;
		})
		.join('\n\n');

	const scriptBlock = importLines
		? `<script lang="ts">\n\t// Generated by domain-builder — hand edits after export are fine.\n${importLines}\n</script>\n\n`
		: '';

	return `${scriptBlock}<div class="t-${input.family}">
${sectionsMarkup}
</div>

<style>
	.t-${input.family} {
		display: grid;
		gap: 2rem;
	}

	.t-section {
		display: grid;
		gap: 1.5rem;
	}

	.t-section--cols-1 {
		grid-template-columns: minmax(0, 1fr);
	}

	.t-section--cols-2 {
		grid-template-columns: repeat(2, minmax(0, 1fr));
	}

	.t-section--cols-3 {
		grid-template-columns: repeat(3, minmax(0, 1fr));
	}

	.t-column {
		display: grid;
		gap: 1rem;
		align-content: start;
	}

	@media (max-width: 960px) {
		.t-section--cols-2,
		.t-section--cols-3 {
			grid-template-columns: minmax(0, 1fr);
		}
	}
</style>
`;
}
